### ISSUE TITLE
Add a Contributing.md file for guiding users on how to setup locally

### ISSUE THREAD

**Issue by m-code12** [coderplex/internship#15]
We could add a Contributing.md file wherein we could guide newcomers to set up this repo locally on their machine and could also guide them on how they could make a pr or contribute by helping them with all the commands and how the command works .

**Comment by m-code12** [comment]
@pbteja1998 @duttakapil Can I work on this issue ?

**Comment by pbteja1998** [comment]
https://docs.coderplex.in is there for that only, right? If there is anything to add, we can add it in there only.

**Comment by pbteja1998** [comment]
@m-code12 assigned this to you.

**Comment by m-code12** [comment]
Okay.Will make a pr soon.
